"""initial schema: floats, profiles, measurements, reports

Revision ID: 5b3ea5e0ed90
Revises: 
Create Date: 2026-08-06 17:33:41.350440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b3ea5e0ed90'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('floats',
    sa.Column('float_id', sa.String(), nullable=False),
    sa.Column('deployment_lat', sa.Float(), nullable=True),
    sa.Column('deployment_lon', sa.Float(), nullable=True),
    sa.Column('deployment_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('float_id')
    )
    op.create_table('reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.Column('ocean_region', sa.String(), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('summary_text', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('float_id', sa.String(), nullable=True),
    sa.Column('cycle_number', sa.Integer(), nullable=True),
    sa.Column('profile_date', sa.DateTime(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('ocean_region', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['float_id'], ['floats.float_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('float_id', 'cycle_number', name='ux_profiles_float_cycle')
    )
    op.create_table('measurements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.Column('pressure_dbar', sa.Float(), nullable=True),
    sa.Column('depth_m', sa.Float(), nullable=True),
    sa.Column('temperature_c', sa.Float(), nullable=True),
    sa.Column('salinity_psu', sa.Float(), nullable=True),
    sa.Column('dissolved_oxygen', sa.Float(), nullable=True),
    sa.Column('chlorophyll', sa.Float(), nullable=True),
    sa.Column('ph', sa.Float(), nullable=True),
    sa.Column('qc_flag', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    # --- Manually added: matches database/schema.sql exactly ---
    # (not expressed as sa.Index() on the ORM models, so autogenerate misses them)
    op.create_index('ix_measurements_profile_id', 'measurements', ['profile_id'])
    op.create_index('ix_profiles_region_date', 'profiles', ['ocean_region', 'profile_date'])


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index('ix_profiles_region_date', table_name='profiles')
    op.drop_index('ix_measurements_profile_id', table_name='measurements')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('measurements')
    op.drop_table('profiles')
    op.drop_table('reports')
    op.drop_table('floats')
    # ### end Alembic commands ###
